version: 2
aliases:

jobs:
  test:
    docker:
      - image: drevops/ci-builder
    steps:
      - checkout
      - run: shellcheck drupal-module-renamer.sh
      - run: bats --tap tests/bats/rename.bats

workflows:
  version: 2
  main:
    jobs:
      - test
