name: Test

on:
  pull_request:
    branches:
      - master
      - 'feature/**'
  push:
    branches:
      - master
      - 'feature/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint
        uses: luizm/action-sh-checker@v0.8.0
        env:
          SHFMT_OPTS: -i 2 -ci -s -d
      - uses: actions/setup-node@v4
      - name: Test
        run: |
          npm i --dev bats
          npm run test
