name: Test

on:
  pull_request:
    branches:
      - main
      - 'feature/**'
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Lint
        uses: luizm/action-sh-checker@v0.9.0
        env:
          SHFMT_OPTS: -i 2 -ci -s -d
      - uses: actions/setup-node@v6
      - run: npm --prefix=tests ci
      - run: npm --prefix=tests run test
